"""Player photo lookup — name → Wikimedia Commons thumbnail URL.

The map is generated by scripts/build_photo_map.py (Wikidata, citizenship-
disambiguated) and committed to data/player_photos.json. Lookups are
diacritic- and case-insensitive so live-feed spellings still match.
"""

import json
import os
import unicodedata
from typing import Dict, Optional

_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "player_photos.json")
_map: Optional[Dict[str, str]] = None


def norm(name: str) -> str:
    return unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().casefold().strip()


def photo_for(name: str) -> Optional[str]:
    global _map
    if _map is None:
        try:
            with open(_PATH, encoding="utf-8") as fh:
                _map = json.load(fh)
        except FileNotFoundError:
            _map = {}
    return _map.get(norm(name))
